version: "3.9"

services:
  freetakserver:
    container_name: freetakserver
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    ports:
      - "8087:8087"     # CoT
      - "8089:8089"     # SSL CoT
      - "8080:8080"     # Data Package
      - "8443:8443"     # SSL Data Package
      - "19023:19023"   # API

    environment:
      FTS_DP_ADDRESS: "3.136.181.249"
      FTS_USER_ADDRESS: "3.136.181.249"
      FTS_API_ADDRESS: "0.0.0.0"
